### ISSUE TITLE
Kat To-Do

### ISSUE THREAD

**Issue by katmeister** [vortic/hanabi#3]
So I can keep track 😸 🎉 
- [x] Improve Played Log readability
- [ ] Figure out better display of Played/Discarded piles
- [ ] Typography tweaks
- [ ] Improved U LOSE 💀 experience
- [ ] Persistent reset button?
- [ ] Dat pink background...
